# Generated by Django 4.2 on 2024-05-01 12:57

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('roll', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=5)),
                ('course_code', models.CharField(max_length=10)),
                ('course_credit', models.FloatField()),
                ('course_title', models.CharField(max_length=255)),
                ('session', models.CharField(choices=[('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23')], default='2018-19', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(blank=True, max_length=50)),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=account.models.profile_pic_uploaded)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('fathers_name', models.CharField(blank=True, max_length=255)),
                ('mothers_name', models.CharField(blank=True, max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=255)),
                ('session', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormFillUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('Regular', 'Regular'), ('Improvement', 'Improvement')], max_length=20)),
                ('student_status', models.CharField(choices=[('C', 'Collegiate'), ('N', 'Non-Collegiate'), ('I', 'Improvement')], max_length=50)),
                ('previous_exam', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('previous_exam_year', models.CharField(max_length=4)),
                ('year', models.CharField(choices=[('Part-1', 'Part-1'), ('Part-2', 'Part-2'), ('Part-3', 'Part-3'), ('Part-4', 'Part-4')], max_length=10)),
                ('semester', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=5)),
                ('academic_year', models.CharField(max_length=5)),
                ('start', models.DateField()),
                ('end_without_fine', models.DateField()),
                ('end_with_fine', models.DateField()),
                ('exam_date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('course', models.ManyToManyField(related_name='course', to='account.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
